services:
  qwen-25-api:
    image: pytorch/pytorch:2.6.0-cuda12.6-cudnn9-devel  # Base image
    container_name: qwen_25_api_container
    working_dir: /app  # Set working directory
    volumes:
      - .:/app  # Mount local project into container
    ports:
      - "8000:8000"  # Map port
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - PYTHONUNBUFFERED=1  # Ensures logs appear instantly
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8000 app.main:app"
    restart: always  # Restart container on failure
